<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-B0O3T20" name="TestAuto.TechAutoTest" tests="2" failures="1" timestamp="28 Jul 2020 15:19:32 GMT" time="0.375" errors="0">
  <testcase name="AdditionTest" time="0.328" classname="TestAuto.TechAutoTest"/>
  <testcase name="SubractionTest" time="0.047" classname="TestAuto.TechAutoTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Not as Expected expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Not as Expected expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at TestAuto.TechAutoTest.SubractionTest(TechAutoTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- SubractionTest -->
</testsuite> <!-- TestAuto.TechAutoTest -->
